# Generated by Django 2.1.3 on 2018-11-15 09:03

import coin.mixin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('btc_krw', 'Bitcoin'), ('xrp_krw', 'XRP'), ('eth_krw', 'Ethereum'), ('bch_krw', 'Bitcoin Cash'), ('zil_krw', 'Zilliqa'), ('etc_krw', 'Ethereum Classic'), ('usdc_krw', 'USD Coin'), ('ltc_krw', 'Litecoin'), ('poly_krw', 'Polymath'), ('btg_krw', 'Bitcoin Gold')], max_length=9, unique=True)),
            ],
            bases=(models.Model, coin.mixin.GetTopTenCoinMixin),
        ),
        migrations.CreateModel(
            name='CoinValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now_value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_day_master', models.BooleanField(default=False)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.Coin')),
            ],
        ),
    ]
